/**
 * Seed Knowledge Bank.
 *
 * These are hand-written, reusable building blocks. They are the only entries
 * that start with status "verified" - anything the model extracts later has to
 * earn its way in (see knowledge/bank.js).
 *
 * `source` is intentionally plain: either "seed" (written by a human for this
 * project) or a description of where the knowledge came from. No invented
 * citations, no statistics.
 */

export const SEED_ENTRIES = [
  // ---------------------------------------------------------------- problems
  { kind: 'problem', name: 'Repetitive manual data entry', description: 'People copy information between systems that do not talk to each other.', examples: ['Invoice re-keying', 'CRM updates after calls', 'Form re-typing from PDFs'], strengths: ['Time cost is measurable and obvious', 'Buyers already budget labour for it'], weaknesses: ['Every ERP vendor claims to solve it', 'Edge cases dominate real deployments'] },
  { kind: 'problem', name: 'Difficult learning curves', description: 'Skill acquisition is slow because feedback is delayed, generic, or absent.', examples: ['Programming', 'Language learning', 'Medical diagnostics', 'Music'], strengths: ['Learners pay for faster feedback', 'Large recurring engagement'], weaknesses: ['Crowded category', 'Motivation and retention are the real product, not content'] },
  { kind: 'problem', name: 'Poor developer tooling', description: 'Developers lose time to unclear errors, missing observability, and manual setup.', examples: ['Debugging CI failures', 'Understanding unfamiliar codebases', 'Local environment drift'], strengths: ['Developers adopt bottom-up without procurement', 'Willing to pay to save hours'], weaknesses: ['Very high expectations', 'Open-source alternatives are free and good'] },
  { kind: 'problem', name: 'Information overload', description: 'More input arrives than a human can triage, so important items are missed.', examples: ['Alert fatigue in ops', 'Email and Slack volume', 'Regulatory change tracking'], strengths: ['Missed items have real cost', 'Clear before/after metric'], weaknesses: ['Triage quality is hard to prove', 'Users distrust automated filtering'] },
  { kind: 'problem', name: 'Knowledge trapped in documents', description: 'Organisations hold answers in PDFs, wikis, and email that nobody can search effectively.', examples: ['Maintenance manuals', 'Contract archives', 'Internal runbooks'], strengths: ['High value per retrieval', 'Incumbents have weak search'], weaknesses: ['Document access and permissions are painful', 'Accuracy expectations are unforgiving'] },
  { kind: 'problem', name: 'Compliance and audit burden', description: 'Regulated teams spend large amounts of time producing evidence that rules were followed.', examples: ['SOC2 evidence collection', 'Medical device records', 'Financial controls'], strengths: ['Budget is mandatory, not discretionary', 'High switching costs once adopted'], weaknesses: ['Long sales cycles', 'Requires domain credibility'] },
  { kind: 'problem', name: 'Coordination across handoffs', description: 'Work stalls when it moves between people, teams, or organisations.', examples: ['Design to engineering', 'Sales to onboarding', 'Clinician to billing'], strengths: ['Delay cost is visible', 'Existing tools stop at team boundaries'], weaknesses: ['Requires both sides to adopt', 'Political ownership of the process'] },
  { kind: 'problem', name: 'Physical-world measurement gaps', description: 'Decisions are made without data because sensing is too expensive or slow.', examples: ['Soil conditions', 'Equipment wear', 'Cold-chain integrity', 'Site progress'], strengths: ['Little software competition', 'Data becomes a durable asset'], weaknesses: ['Hardware cost and calibration', 'Deployment and maintenance logistics'] },
  { kind: 'problem', name: 'Trust and verification', description: 'One party cannot cheaply confirm what another party claims.', examples: ['Credentials', 'Product provenance', 'Contractor work quality', 'AI-generated content'], strengths: ['Verification has direct monetary value'], weaknesses: ['Adversaries actively evade', 'Needs a verification source of truth'] },
  { kind: 'problem', name: 'Small-business back office', description: 'Owners of small firms do finance, scheduling, and admin themselves, badly.', examples: ['Trades', 'Clinics', 'Studios', 'Independent retailers'], strengths: ['Clear labour savings', 'Underserved by enterprise software'], weaknesses: ['Low IT literacy and low patience', 'High support cost per customer'] },
  { kind: 'problem', name: 'Slow expert access', description: 'Getting a qualified human opinion takes days and costs a lot.', examples: ['Legal review', 'Second medical opinion', 'Engineering design review'], strengths: ['High price anchor from existing experts'], weaknesses: ['Liability and licensing', 'Experts are the bottleneck and the competition'] },
  { kind: 'problem', name: 'Waste and idle capacity', description: 'Assets, materials, or time sit unused while someone else needs them.', examples: ['Equipment rental', 'Excess inventory', 'Unused compute', 'Empty seats'], strengths: ['Value is created from nothing new', 'Two-sided network effects possible'], weaknesses: ['Marketplaces are cold-start hard', 'Supply quality is inconsistent'] },

  // ------------------------------------------------------------ technologies
  { kind: 'technology', name: 'Large language models', description: 'General text understanding and generation, hosted or local.', examples: ['Summarisation', 'Extraction', 'Drafting', 'Classification'], strengths: ['Broad applicability', 'Rapidly improving quality'], weaknesses: ['Hallucination risk', 'Token cost scales with volume', 'Weak at precise arithmetic'] },
  { kind: 'technology', name: 'Local / on-device AI', description: 'Models that run on the user machine, so data never leaves.', examples: ['Ollama-hosted models', 'ONNX runtime', 'WebGPU inference'], strengths: ['Privacy is a real differentiator', 'No per-call cost', 'Works offline'], weaknesses: ['Hardware limits quality', 'Installation friction', 'Model updates are manual'] },
  { kind: 'technology', name: 'Computer vision', description: 'Extracting structure and meaning from images and video.', examples: ['Defect detection', 'Document layout analysis', 'Object counting'], strengths: ['Replaces expensive human inspection'], weaknesses: ['Lighting and angle variance', 'Labelling cost', 'Rare cases dominate'] },
  { kind: 'technology', name: 'OCR and document parsing', description: 'Converting scans, photos, and PDFs into structured text.', examples: ['Invoice capture', 'Handwritten forms', 'Table extraction'], strengths: ['Mature and cheap', 'Directly removes data entry'], weaknesses: ['Accuracy drops on handwriting and poor scans', 'Requires human review loop'] },
  { kind: 'technology', name: 'Browser automation', description: 'Driving a real browser to act on systems without APIs.', examples: ['Playwright scripts', 'Extension-based capture', 'Form filling'], strengths: ['Works with legacy systems', 'Fast to prototype'], weaknesses: ['Brittle against UI changes', 'Terms-of-service and bot-detection risk'] },
  { kind: 'technology', name: 'Speech recognition and synthesis', description: 'Turning audio into text and text into audio.', examples: ['Dictation', 'Call transcription', 'Voice interfaces'], strengths: ['Hands-free operation in the field', 'Accessibility value'], weaknesses: ['Noisy environments', 'Accent and jargon accuracy', 'Latency'] },
  { kind: 'technology', name: 'Vector search and embeddings', description: 'Semantic retrieval over large document collections.', examples: ['RAG over manuals', 'Similar-case lookup', 'Deduplication'], strengths: ['Retrieval quality beats keyword search', 'Cheap at scale'], weaknesses: ['Chunking decisions dominate quality', 'Embeddings are opaque to users'] },
  { kind: 'technology', name: 'Structured data extraction', description: 'Constraining model output to schemas, tables, and enums.', examples: ['JSON schema output', 'Function calling', 'Form normalisation'], strengths: ['Makes model output usable by software', 'Reduces post-processing'], weaknesses: ['Schema drift', 'Small models violate constraints'] },
  { kind: 'technology', name: 'Sensor and IoT telemetry', description: 'Collecting physical measurements over time.', examples: ['Accelerometers', 'Temperature loggers', 'Power meters'], strengths: ['Creates proprietary datasets'], weaknesses: ['Hardware, batteries, connectivity', 'Installation cost per site'] },
  { kind: 'technology', name: 'Simulation and digital twins', description: 'Modelling a system so changes can be tested before deployment.', examples: ['Factory layout', 'Logistics routing', 'Circuit behaviour'], strengths: ['High value per run', 'Hard to replicate'], weaknesses: ['Model fidelity is expensive', 'Needs domain data'] },
  { kind: 'technology', name: 'Differential privacy and secure aggregation', description: 'Learning from sensitive data without exposing individuals.', examples: ['Health cohorts', 'Salary benchmarks', 'Telemetry'], strengths: ['Unlocks data nobody else can use'], weaknesses: ['Complexity', 'Utility loss', 'Hard to explain to buyers'] },
  { kind: 'technology', name: 'Edge deployment and WebGPU', description: 'Running compute in the browser or on cheap local hardware.', examples: ['In-browser inference', 'WASM pipelines', 'Raspberry Pi agents'], strengths: ['No server bill', 'Low latency'], weaknesses: ['Device variance', 'Limited model size'] },

  // --------------------------------------------------------- business models
  { kind: 'business-model', name: 'Subscription (SaaS)', description: 'Recurring monthly or annual fee for continued access.', examples: ['Per-seat plans', 'Team tiers'], strengths: ['Predictable revenue', 'Familiar to buyers'], weaknesses: ['Churn must be actively fought', 'Requires ongoing perceived value'] },
  { kind: 'business-model', name: 'Usage-based pricing', description: 'Charge per unit consumed: documents, minutes, API calls, seats active.', examples: ['Per-scan pricing', 'Per-minute transcription'], strengths: ['Aligns cost with value', 'Low entry barrier'], weaknesses: ['Unpredictable for the buyer', 'Revenue is volatile'] },
  { kind: 'business-model', name: 'Freemium', description: 'Free tier for adoption, paid tier for scale or collaboration.', examples: ['Free single user', 'Paid teams'], strengths: ['Fast top-of-funnel', 'Self-serve conversion'], weaknesses: ['Free users cost money', 'Conversion rates are usually low'] },
  { kind: 'business-model', name: 'One-time purchase / perpetual licence', description: 'Single payment for a product that keeps working.', examples: ['Desktop utilities', 'Pro plugins'], strengths: ['Simple to sell', 'No churn accounting'], weaknesses: ['Needs constant new customers', 'No recurring revenue'] },
  { kind: 'business-model', name: 'Licensing and white-label', description: 'Sell the capability to another company who resells it.', examples: ['OEM SDK', 'Bank-embedded feature'], strengths: ['Large contracts', 'Someone else does distribution'], weaknesses: ['Long negotiations', 'Loss of end-user relationship'] },
  { kind: 'business-model', name: 'Marketplace with take rate', description: 'Match supply and demand and charge a percentage.', examples: ['Equipment hire', 'Expert bookings'], strengths: ['Network effects compound'], weaknesses: ['Cold start on both sides', 'Disintermediation risk'] },
  { kind: 'business-model', name: 'API pricing', description: 'Sell programmatic access per request or per key.', examples: ['Extraction API', 'Scoring API'], strengths: ['Developers adopt without sales', 'Scales linearly'], weaknesses: ['Commodity pressure', 'Requires reliability engineering'] },
  { kind: 'business-model', name: 'Outcome-based pricing', description: 'Charge only when a measurable result occurs.', examples: ['Per recovered invoice', 'Per resolved ticket'], strengths: ['Removes buyer risk', 'Strong differentiation'], weaknesses: ['Attribution is contested', 'Revenue lags delivery'] },
  { kind: 'business-model', name: 'Services and productised consulting', description: 'Human expertise delivered with a fixed scope and price.', examples: ['Audit sprint', 'Migration package'], strengths: ['High margin on expertise', 'Fast to start'], weaknesses: ['Does not scale without hiring', 'Revenue stops when you stop'] },
  { kind: 'business-model', name: 'Data and benchmarking reports', description: 'Aggregate anonymised data sold as insight.', examples: ['Salary benchmarks', 'Ops performance index'], strengths: ['One dataset, many buyers'], weaknesses: ['Needs scale before value', 'Legal exposure'] },
  { kind: 'business-model', name: 'Hardware plus software', description: 'Device sale with a recurring software layer.', examples: ['Sensor plus dashboard'], strengths: ['Physical lock-in', 'Upfront cash'], weaknesses: ['Inventory risk', 'Support burden'] },
  { kind: 'business-model', name: 'Community and education membership', description: 'Recurring fee for content, cohort, and access to peers.', examples: ['Cohort courses', 'Paid communities'], strengths: ['Low marginal cost', 'Loyal audience'], weaknesses: ['Depends on personal brand', 'Content treadmill'] },

  // ---------------------------------------------------------- distribution
  { kind: 'distribution', name: 'Web application', description: 'Browser-based product reached by search, ads, or referral.', examples: ['SaaS landing page', 'Self-serve signup'], strengths: ['No install friction', 'Instant updates'], weaknesses: ['Discovery is expensive', 'Crowded search results'] },
  { kind: 'distribution', name: 'Browser extension', description: 'Software installed into the browser that works on top of other sites.', examples: ['Capture tools', 'In-page assistants'], strengths: ['Sits inside the user existing workflow', 'Cheap to distribute via store'], weaknesses: ['Platform policy risk', 'Limited compute'] },
  { kind: 'distribution', name: 'App stores (mobile/desktop)', description: 'Distribution through Apple, Google, or Microsoft marketplaces.', examples: ['iOS utility', 'Mac menu-bar app'], strengths: ['Built-in discovery and payments'], weaknesses: ['Platform fees', 'Review friction'] },
  { kind: 'distribution', name: 'Developer API and SDK', description: 'Reach builders who embed the capability in their own products.', examples: ['REST API', 'Python SDK'], strengths: ['Each customer multiplies reach', 'Low support surface'], weaknesses: ['Requires excellent docs', 'Long evaluation by engineers'] },
  { kind: 'distribution', name: 'Open source with paid layer', description: 'Free core to earn trust and adoption, paid hosted or enterprise tier.', examples: ['Self-host community edition'], strengths: ['Credibility with technical buyers', 'Inbound contributions'], weaknesses: ['Monetisation boundary is contested', 'Support expectations'] },
  { kind: 'distribution', name: 'Direct B2B sales', description: 'Selling to companies through demos, pilots, and procurement.', examples: ['Enterprise pilot', 'Departmental deal'], strengths: ['Large contract values', 'Deep feedback'], weaknesses: ['Slow cycle', 'Founder time is the bottleneck'] },
  { kind: 'distribution', name: 'Channel partners and resellers', description: 'Existing vendors sell your product to their installed base.', examples: ['MSPs', 'Consultancies', 'Industry associations'], strengths: ['Access to trusted relationships'], weaknesses: ['Margin share', 'Loss of messaging control'] },
  { kind: 'distribution', name: 'Education institutions', description: 'Selling to schools, colleges, and training providers.', examples: ['Campus licence', 'Curriculum bundle'], strengths: ['Bulk seats', 'Long retention'], weaknesses: ['Budget cycles', 'Procurement friction'] },
  { kind: 'distribution', name: 'Templates and plugin ecosystems', description: 'Distribution through someone else platform marketplace.', examples: ['Figma plugin', 'Shopify app', 'VS Code extension', 'Notion template'], strengths: ['Marketplace brings intent traffic'], weaknesses: ['Platform dependency', 'Copycat risk'] },
  { kind: 'distribution', name: 'Content and community led', description: 'Audience built through writing, video, or a niche community.', examples: ['Technical newsletter', 'Conference talks'], strengths: ['Cheap trust building', 'Compounding'], weaknesses: ['Slow', 'Depends on consistency'] },
  { kind: 'distribution', name: 'Embedding in existing workflow tools', description: 'Showing up inside the software people already use all day.', examples: ['Slack and Teams apps', 'CRM plugins', 'EHR integrations'], strengths: ['Zero context switch', 'Fast habit formation'], weaknesses: ['Platform API limits', 'Certification requirements'] },

  // ---------------------------------------------------------- monetisation
  { kind: 'monetization', name: 'Per-seat licence', description: 'Charge for each named user.', examples: ['Team plan per user per month'], strengths: ['Simple to forecast', 'Scales with customer size'], weaknesses: ['Buyers minimise seats', 'Bad fit for sporadic use'] },
  { kind: 'monetization', name: 'Per-unit transaction fee', description: 'Charge for each processed item.', examples: ['Per document', 'Per scan', 'Per API call'], strengths: ['Direct value alignment'], weaknesses: ['Encourages batching to avoid fees', 'Revenue variance'] },
  { kind: 'monetization', name: 'Tiered feature gating', description: 'Basic free or cheap, advanced capabilities behind higher tiers.', examples: ['Export, SSO, audit logs in the top tier'], strengths: ['Natural upgrade path'], weaknesses: ['Requires clear tier value', 'Resentment at arbitrary limits'] },
  { kind: 'monetization', name: 'Setup plus recurring', description: 'One-time implementation fee with ongoing subscription.', examples: ['Onboarding and integration fee'], strengths: ['Covers real deployment cost'], weaknesses: ['Raises initial friction'] },
  { kind: 'monetization', name: 'Revenue share or success fee', description: 'Take a percentage of money the customer earns or recovers.', examples: ['Recovery services', 'Marketplace take rate'], strengths: ['Zero-risk framing'], weaknesses: ['Attribution disputes', 'Cash-flow lag'] },
  { kind: 'monetization', name: 'Credit packs and prepaid capacity', description: 'Customer buys blocks of usage in advance.', examples: ['Credit bundles', 'Prepaid minutes'], strengths: ['Upfront cash', 'Low commitment'], weaknesses: ['Breakage invites distrust', 'Poor fit for heavy users'] },
  { kind: 'monetization', name: 'Enterprise add-ons', description: 'Charge separately for compliance, security, and control features.', examples: ['SSO', 'Audit log export', 'On-prem deployment', 'DPA'], strengths: ['High margin', 'Required by procurement anyway'], weaknesses: ['Only relevant later'] },
  { kind: 'monetization', name: 'Training and certification', description: 'Sell education around the product.', examples: ['Operator certification', 'Admin training'], strengths: ['Increases stickiness', 'Extra revenue line'], weaknesses: ['Requires content upkeep'] },

  // --------------------------------------------------------------- audiences
  { kind: 'audience', name: 'Solo developers and indie hackers', description: 'Individuals building and shipping their own software.', examples: ['Freelancers', 'Side-project founders'], strengths: ['Fast adoption', 'Public feedback'], weaknesses: ['Low budget', 'High churn'] },
  { kind: 'audience', name: 'Small and medium businesses', description: 'Companies from a handful to a few hundred staff without big IT teams.', examples: ['Trades', 'Agencies', 'Clinics', 'Retailers'], strengths: ['Real pain, real budget', 'Underserved'], weaknesses: ['Needs hand-holding', 'Fragmented by industry'] },
  { kind: 'audience', name: 'Regulated industries', description: 'Sectors with formal compliance requirements.', examples: ['Healthcare', 'Finance', 'Legal', 'Public sector'], strengths: ['High willingness to pay', 'Strong retention'], weaknesses: ['Slow procurement', 'Certification burden'] },
  { kind: 'audience', name: 'Field and deskless workers', description: 'People who work away from a keyboard.', examples: ['Technicians', 'Nurses', 'Drivers', 'Site inspectors'], strengths: ['Underserved by software', 'Mobile-first opportunity'], weaknesses: ['Connectivity and device limits', 'Hard to reach for marketing'] },
  { kind: 'audience', name: 'Researchers and analysts', description: 'People who turn data into conclusions.', examples: ['Academic labs', 'Market analysts', 'Data scientists'], strengths: ['Deep engagement', 'Credibility transfer'], weaknesses: ['Small market', 'Demand reproducibility'] },
  { kind: 'audience', name: 'Operations and back-office teams', description: 'People who keep processes running.', examples: ['Finance ops', 'Support ops', 'Logistics coordinators'], strengths: ['Buy to remove toil', 'Measurable savings'], weaknesses: ['Integration work is heavy'] },
  { kind: 'audience', name: 'Educators and trainers', description: 'People responsible for teaching others.', examples: ['Teachers', 'Corporate trainers', 'Course creators'], strengths: ['Large audience', 'Mission-driven advocacy'], weaknesses: ['Very tight budgets', 'Seasonal cycles'] },
  { kind: 'audience', name: 'Consumers with a hobby or obligation', description: 'Individuals paying to be better at or done with something.', examples: ['Home maintenance', 'Fitness', 'Taxes', 'Collecting'], strengths: ['Emotional purchase drivers', 'Large volume'], weaknesses: ['High acquisition cost', 'Low tolerance for friction'] },
];

export const KINDS = ['problem', 'technology', 'business-model', 'distribution', 'monetization', 'audience'];

export const KIND_LABELS = {
  problem: 'Problems',
  technology: 'Technologies',
  'business-model': 'Business models',
  distribution: 'Distribution',
  monetization: 'Monetization',
  audience: 'Audiences',
};
